<?php
function menu() {
	
	echo "<nav>";
	echo "<a id='resp-menu' class='responsive-menu' href='#'><i class='fa fa-reorder'></i> Menu</a>";
	echo "<ul class='menu'>";
	echo "<li><a id='homer' href='#'><i class='fa fa-home'></i> Home</a></li>";
	echo "<li><a><i class='fa fa-tags'></i> Products</a>";
	echo "<ul class='sub-menu'>";
	echo "<li><a href='#'>ezyInvertory</a>";			      
	echo "<ul>";
	echo "<li><a href='micro.php'><span>ezyInvertory (Micro Version)</span></a></li>";
	echo "<li><a href='mini.php'><span>ezyInvertory (Mini Version)</span></a></li>";
	echo "<li><a href='macro.php'><span>ezyInvertory (Macro Version)</span></a></li>";
	echo "<li><a href='myanmar.php'><span>ezyInvertory (Myanmar Version)</span></a></li>";
	echo "</ul>";
	echo "</li>";
	echo "<li><a href='pweyone.php'>Pwe Yone</a></li>";
	echo "<li><a href='pawnshop.php'><span>Pawn Shop</span></a></li>";
	echo "<li><a href='gold.php'><span>Gold & Jewelry</span></a></li>";
	echo "<li><a href='easymobile.php'><span>ezyMobile</span>";
	echo "<li><a href='pharmacy.php'><span>Pharmacy Management</span></a></li>";
	echo "<li><a href='eazylab.php'><span>Laboratory System</span></a></li>";
	echo "<li><a href='eazyfinancial.php'><span>Easy Financial</span></a></li>";
	echo "<li><a href='xchange.php'><span>Easy Xchange</span></a></li>";
	echo "</ul>";
	echo "</li>";
	echo "<li><a><i class='fa fa-cog'></i> Services</a>";
	echo "<ul class='sub-menu'>";
	echo "<li><a href='product.php'>Window Service</a></li>";
	echo "<li><a href='host.php'>Web Service</a></li>";
	echo "<li><a  href='domain.php'> Domain</a></li>";
	echo "</ul>";
	echo "</li>";
	echo "<li><a  href='about.php'><i class='fa fa-user'></i> About Us</a></li>";
	echo "<li><a  href='contact.php'><i class='fa fa-envelope'></i> Contact Us</a></li>";
	echo "</ul>";
	echo "</nav>";
	}

function about_menu() {
	echo "<nav>";
	echo"<a id='resp-menu' class='responsive-menu' href='#'><i class='fa fa-reorder'></i>Menu</a>";
	echo "<ul class='menu'>";
	echo "<li><a href='index.php'><i class='fa fa-home'></i> Home</a></li>";
	echo "<li><a><i class='fa fa-tags'></i> Products</a>";
	echo "<ul class='sub-menu'>";
	echo "<li><a href='#'>ezyInvertory</a>";			      
	echo "<ul>";
	echo "<li><a href='micro.php'><span>ezyInvertory (Micro Version)</span></a></li>";
	echo "<li><a href='mini.php'><span>ezyInvertory (Mini Version)</span></a></li>";
	echo "<li><a href='macro.php'><span>ezyInvertory (Macro Version)</span></a></li>";
	echo "<li><a href='myanmar.php'><span>ezyInvertory (Myanmar Version)</span></a></li>";
	echo "</ul>";
	echo "</li>";
	echo "<li><a href='pweyone.php'>Pwe Yone</a></li>";
	echo "<li><a href='pawnshop.php'><span>Pawn Shop</span></a></li>";
	echo "<li><a href='gold.php'><span>Gold & Jewelry</span></a></li>";
	echo "<li><a href='easymobile.php'><span>ezyMobile</span>";
	echo "<li><a href='pharmacy.php'><span>Pharmacy Management</span></a></li>";
	echo "<li><a href='eazylab.php'><span>Laboratory System</span></a></li>";
	echo "<li><a href='eazyfinancial.php'><span>Easy Financial</span></a></li>";
	echo "<li><a href='xchange.php'><span>Easy Xchange</span></a></li>";
	echo "</ul>";
	echo "</li>";
	echo "<li><a><i class='fa fa-cog'></i> Services</a>";
	echo "<ul class='sub-menu'>";
	echo "<li><a href='product.php'>Window Service</a></li>";
	echo "<li><a href='host.php'>Web Service</a></li>";
	echo "<li><a  href='domain.php'> Domain</a></li>";
	echo "</ul>";
	echo "</li>";
	echo "<li><a id='homer' href='about.php'><i class='fa fa-user'></i> About Us</a></li>";
	echo "<li><a  href='contact.php'><i class='fa fa-envelope'></i> Contact Us</a></li>";
	echo "</ul>";
	echo "</nav>";
}

function contact_menu() {
	echo "<nav>";
	echo"<a id='resp-menu' class='responsive-menu' href='#'><i class='fa fa-reorder'></i>Menu</a>";
	echo "<ul class='menu'>";
	echo "<li><a href='index.php'><i class='fa fa-home'></i> Home</a></li>";
	echo "<li><a><i class='fa fa-tags'></i> Products</a>";
	echo "<ul class='sub-menu'>";
	echo "<li><a href='#'>ezyInvertory</a>";			      
	echo "<ul>";
	echo "<li><a href='micro.php'><span>ezyInvertory (Micro Version)</span></a></li>";
	echo "<li><a href='mini.php'><span>ezyInvertory (Mini Version)</span></a></li>";
	echo "<li><a href='macro.php'><span>ezyInvertory (Macro Version)</span></a></li>";
	echo "<li><a href='myanmar.php'><span>ezyInvertory (Myanmar Version)</span></a></li>";
	echo "</ul>";
	echo "</li>";
	echo "<li><a href='pweyone.php'>Pwe Yone</a></li>";
	echo "<li><a href='pawnshop.php'><span>Pawn Shop</span></a></li>";
	echo "<li><a href='gold.php'><span>Gold & Jewelry</span></a></li>";
	echo "<li><a href='easymobile.php'><span>ezyMobile</span>";
	echo "<li><a href='pharmacy.php'><span>Pharmacy Management</span></a></li>";
	echo "<li><a href='eazylab.php'><span>Laboratory System</span></a></li>";
	echo "<li><a href='eazyfinancial.php'><span>Easy Financial</span></a></li>";
	echo "<li><a href='xchange.php'><span>Easy Xchange</span></a></li>";
	echo "</ul>";
	echo "</li>";
	echo "<li><a><i class='fa fa-cog'></i> Services</a>";
	echo "<ul class='sub-menu'>";
	echo "<li><a href='product.php'>Window Service</a></li>";
	echo "<li><a href='host.php'>Web Service</a></li>";
	echo "<li><a  href='domain.php'> Domain</a></li>";
	echo "</ul>";
	echo "</li>";
	echo "<li><a href='about.php'><i class='fa fa-user'></i> About Us</a></li>";
	echo "<li><a id='homer' href='contact.php'><i class='fa fa-envelope'></i> Contact Us</a></li>";
	echo "</ul>";
	echo "</nav>";
}

function product_menu() {
	echo "<section class = 'first'>";
	echo "<nav>";
	echo"<a id='resp-menu' class='responsive-menu' href='#'><i class='fa fa-reorder'></i>Menu</a>";
	echo "<ul class='menu'>";
	echo "<li><a href='index.php'><i class='fa fa-home'></i> Home</a></li>";
	echo "<li><a><i class='fa fa-tags'></i> Products</a>";
	echo "<ul class='sub-menu'>";
	echo "<li><a href='#'>ezyInvertory</a>";			      
	echo "<ul>";
	echo "<li><a href='micro.php'><span>ezyInvertory (Micro Version)</span></a></li>";
	echo "<li><a href='mini.php'><span>ezyInvertory (Mini Version)</span></a></li>";
	echo "<li><a href='macro.php'><span>ezyInvertory (Macro Version)</span></a></li>";
	echo "<li><a href='myanmar.php'><span>ezyInvertory (Myanmar Version)</span></a></li>";
	echo "</ul>";
	echo "</li>";
	echo "<li><a href='pweyone.php'>Pwe Yone</a></li>";
	echo "<li><a href='pawnshop.php'><span>Pawn Shop</span></a></li>";
	echo "<li><a href='gold.php'><span>Gold & Jewelry</span></a></li>";
	echo "<li><a href='easymobile.php'><span>ezyMobile</span>";
	echo "<li><a href='pharmacy.php'><span>Pharmacy Management</span></a></li>";
	echo "<li><a href='eazylab.php'><span>Laboratory System</span></a></li>";
	echo "<li><a href='eazyfinancial.php'><span>Easy Financial</span></a></li>";
	echo "<li><a href='xchange.php'><span>Easy Xchange</span></a></li>";
	echo "</ul>";
	echo "</li>";
	echo "<li><a><i class='fa fa-cog'></i> Services</a>";
	echo "<ul class='sub-menu'>";
	echo "<li><a href='product.php'>Window Service</a></li>";
	echo "<li><a href='host.php'>Web Service</a></li>";
	echo "<li><a  href='domain.php'> Domain</a></li>";
	echo "</ul>";
	echo "</li>";
	echo "<li><a  href='about.php'><i class='fa fa-user'></i> About Us</a></li>";
	echo "<li><a  href='contact.php'><i class='fa fa-envelope'></i> Contact Us</a></li>";
	echo "</ul>";
	echo "</nav>";
	echo "</section>";
}

function host_menu() {
	echo "<nav>";
	echo"<a id='resp-menu' class='responsive-menu' href='#'><i class='fa fa-reorder'></i>Menu</a>";
	echo "<ul class='menu'>";
	echo "<li><a href='index.php'><i class='fa fa-home'></i> Home</a></li>";
	echo "<li><a><i class='fa fa-tags'></i> Products</a>";
	echo "<ul class='sub-menu'>";
	echo "<li><a href='#'>ezyInvertory</a>";			      
	echo "<ul>";
	echo "<li><a href='micro.php'><span>ezyInvertory (Micro Version)</span></a></li>";
	echo "<li><a href='mini.php'><span>ezyInvertory (Mini Version)</span></a></li>";
	echo "<li><a href='macro.php'><span>ezyInvertory (Macro Version)</span></a></li>";
	echo "<li><a href='myanmar.php'><span>ezyInvertory (Myanmar Version)</span></a></li>";
	echo "</ul>";
	echo "</li>";
	echo "<li><a href='pweyone.php'>Pwe Yone</a></li>";
	echo "<li><a href='pawnshop.php'><span>Pawn Shop</span></a></li>";
	echo "<li><a href='gold.php'><span>Gold & Jewelry</span></a></li>";
	echo "<li><a href='easymobile.php'><span>ezyMobile</span>";
	echo "<li><a href='pharmacy.php'><span>Pharmacy Management</span></a></li>";
	echo "<li><a href='eazylab.php'><span>Laboratory System</span></a></li>";
	echo "<li><a href='eazyfinancial.php'><span>Easy Financial</span></a></li>";
	echo "<li><a href='xchange.php'><span>Easy Xchange</span></a></li>";
	echo "</ul>";
	echo "</li>";
	echo "<li><a><i class='fa fa-cog'></i> Services</a>";
	echo "<ul class='sub-menu'>";
	echo "<li><a href='product.php'>Window Service</a></li>";
	echo "<li><a href='host.php'>Web Service</a></li>";
	echo "<li><a  href='domain.php'> Domain</a></li>";
	echo "</ul>";
	echo "</li>";
	echo "<li><a  href='about.php'><i class='fa fa-user'></i> About Us</a></li>";
	echo "<li><a  href='contact.php'><i class='fa fa-envelope'></i> Contact Us</a></li>";
	echo "</ul>";
	echo "</nav>";
}
function services_menu() {
	echo "<nav>";
	echo"<a id='resp-menu' class='responsive-menu' href='#'><i class='fa fa-reorder'></i>Menu</a>";
	echo "<ul class='menu'>";
	echo "<li><a href='index.php'><i class='fa fa-home'></i> Home</a></li>";
	echo "<li><a><i class='fa fa-tags'></i> Products</a>";
	echo "<ul class='sub-menu'>";
	echo "<li><a href='#'>ezyInvertory</a>";			      
	echo "<ul>";
	echo "<li><a href='micro.php'><span>ezyInvertory (Micro Version)</span></a></li>";
	echo "<li><a href='mini.php'><span>ezyInvertory (Mini Version)</span></a></li>";
	echo "<li><a href='macro.php'><span>ezyInvertory (Macro Version)</span></a></li>";
	echo "<li><a href='myanmar.php'><span>ezyInvertory (Myanmar Version)</span></a></li>";
	echo "</ul>";
	echo "</li>";
	echo "<li><a href='pweyone.php'>Pwe Yone</a></li>";
	echo "<li><a href='pawnshop.php'><span>Pawn Shop</span></a></li>";
	echo "<li><a href='gold.php'><span>Gold & Jewelry</span></a></li>";
	echo "<li><a href='easymobile.php'><span>ezyMobile</span>";
	echo "<li><a href='pharmacy.php'><span>Pharmacy Management</span></a></li>";
	echo "<li><a href='eazylab.php'><span>Laboratory System</span></a></li>";
	echo "<li><a href='eazyfinancial.php'><span>Easy Financial</span></a></li>";
	echo "<li><a href='xchange.php'><span>Easy Xchange</span></a></li>";
	echo "</ul>";
	echo "</li>";
	echo "<li><a><i class='fa fa-cog'></i> Services</a>";
	echo "<ul class='sub-menu'>";
	echo "<li><a href='product.php'>Window Service</a></li>";
	echo "<li><a href='host.php'>Web Service</a></li>";
	echo "<li><a  href='domain.php'> Domain</a></li>";
	echo "</ul>";
	echo "</li>";
	echo "<li><a  href='about.php'><i class='fa fa-user'></i> About Us</a></li>";
	echo "<li><a  href='contact.php'><i class='fa fa-envelope'></i> Contact Us</a></li>";
	echo "</ul>";
	echo "</nav>";
}

?>